"""
Signal class - represents a trading signal generated by the scanner.
"""

from enum import Enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, Optional


class SignalType(Enum):
    """Types of trading signals."""
    BUY = "BUY"
    SELL = "SELL"
    SHORT = "SHORT"
    COVER = "COVER"
    HOLD = "HOLD"


@dataclass
class Signal:
    """
    Represents a trading signal.
    
    A signal is the OUTPUT of the scanner/signal_engine.
    It contains all information needed for decision making and execution.
    """
    
    # Core identification
    ticker: str
    signal_type: SignalType
    timestamp: datetime = field(default_factory=datetime.utcnow)
    signal_id: str = field(default="")
    
    # Price information
    current_price: float = 0.0
    entry_price: float = 0.0
    profit_target: float = 0.0
    stop_loss: float = 0.0
    
    # Analysis scores (0-100)
    technical_score: float = 0.0
    ml_score: float = 0.0
    sentiment_score: float = 0.0
    overall_confidence: float = 0.0
    
    # Metadata
    reason: str = ""  # Why this signal was generated
    analysis_data: Dict[str, Any] = field(default_factory=dict)
    
    # Tracking
    created_at: datetime = field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
    
    def __post_init__(self):
        """Generate signal ID if not provided."""
        if not self.signal_id:
            self.signal_id = f"{self.ticker}_{self.signal_type.value}_{int(self.timestamp.timestamp())}"
    
    @property
    def is_long(self) -> bool:
        """Returns True if this is a long signal (BUY)."""
        return self.signal_type == SignalType.BUY
    
    @property
    def is_short(self) -> bool:
        """Returns True if this is a short signal (SHORT)."""
        return self.signal_type == SignalType.SHORT
    
    @property
    def potential_profit_pct(self) -> float:
        """Calculate potential profit percentage."""
        if self.entry_price <= 0:
            return 0.0
        return ((self.profit_target - self.entry_price) / self.entry_price) * 100
    
    @property
    def potential_loss_pct(self) -> float:
        """Calculate potential loss percentage."""
        if self.entry_price <= 0:
            return 0.0
        return ((self.stop_loss - self.entry_price) / self.entry_price) * 100
    
    @property
    def reward_to_risk(self) -> float:
        """Calculate risk/reward ratio."""
        risk = abs(self.potential_loss_pct)
        if risk == 0:
            return 0.0
        return self.potential_profit_pct / risk
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            'ticker': self.ticker,
            'signal_type': self.signal_type.value,
            'signal_id': self.signal_id,
            'timestamp': self.timestamp.isoformat(),
            'current_price': self.current_price,
            'entry_price': self.entry_price,
            'profit_target': self.profit_target,
            'stop_loss': self.stop_loss,
            'technical_score': self.technical_score,
            'ml_score': self.ml_score,
            'sentiment_score': self.sentiment_score,
            'overall_confidence': self.overall_confidence,
            'reason': self.reason,
            'potential_profit_pct': self.potential_profit_pct,
            'potential_loss_pct': self.potential_loss_pct,
            'reward_to_risk': self.reward_to_risk,
        }
    
    def __repr__(self) -> str:
        return (
            f"Signal({self.ticker} {self.signal_type.value} @ ${self.entry_price:.2f} "
            f"Confidence: {self.overall_confidence:.0f}% "
            f"R:R {self.reward_to_risk:.2f})"
        )
